#!/bin/sh
#
# Install or reload the bridge as a login agent. Idempotent — run it again
# after editing this script, or after changing code that needs a restart.
#
#   service/install.sh              install / reload
#   launchctl kickstart -k gui/$UID/local.claude-in-qq    restart
#   launchctl bootout gui/$UID/local.claude-in-qq         stop & unload
#
# The plist is generated here rather than committed, because a working one has
# to name this machine: absolute home paths, the PATH of the shell you actually
# use, and a no_proxy list that may carry internal hostnames. None of that
# belongs in a repository. Run this from an interactive shell so the proxy and
# PATH it reads are the ones you really have.

set -eu

LABEL=local.claude-in-qq
ROOT=$(cd "$(dirname "$0")/.." && pwd)
DEST="$HOME/Library/LaunchAgents/$LABEL.plist"
TARGET="gui/$(id -u)"
LOG_DIR="${QQ_STATE_DIR:-$HOME/.claude/channels/qq}"

# Unload first, so the survivors of the check below are only the hand-started
# ones. Two bridges hold the same gateway session and fight over it — messages
# land in whichever won the last reconnect.
launchctl bootout "$TARGET/$LABEL" 2>/dev/null || true
sleep 1

# The executable comes from `args`, not from `comm`: macOS truncates the comm
# column, so a bun under a long home path shows up as "/Users/name" and never
# matches. `pgrep -f` is no good either — it also matches any shell whose
# command line merely mentions the path, including the one used to kill it.
running=$(ps -axo pid=,args= | awk '$2 ~ /bun$/ && index($0, "src/index.ts") {print}')
if [ -n "$running" ]; then
  echo "! 有手动启动的 bridge 在跑，先停掉它："
  echo "$running"
  echo "  kill $(printf '%s' "$running" | awk '{print $1}' | tr '\n' ' ')"
  exit 1
fi

# Taken from the environment rather than defaulted to anything, so this script
# carries no trace of the machine it was written on.
PROXY=${https_proxy:-${HTTPS_PROXY:-}}
NOPROXY=${no_proxy:-${NO_PROXY:-}}
if [ -z "$PROXY" ]; then
  echo "! 环境里没有 https_proxy，生成的服务会直连。"
  echo "  若 api.anthropic.com 在本地需要代理，请在交互式 shell 里重跑本脚本。"
fi

# launchd inherits no shell profile, so a PATH that lost /opt/homebrew means
# every command the agent runs over QQ comes back "not found".
case ":$PATH:" in
  *:/opt/homebrew/bin:*) ;;
  *) echo "! 当前 PATH 里没有 /opt/homebrew/bin，看起来不是交互式 shell 的 PATH" ;;
esac

xml() { printf '%s' "$1" | sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g'; }
pair() { [ -n "$2" ] && printf '        <key>%s</key>\n        <string>%s</string>\n' "$1" "$(xml "$2")"; }

PROXY_ENV=$(
  pair http_proxy "$PROXY"
  pair https_proxy "$PROXY"
  pair HTTP_PROXY "$PROXY"
  pair HTTPS_PROXY "$PROXY"
  pair no_proxy "$NOPROXY"
  pair NO_PROXY "$NOPROXY"
)

mkdir -p "$LOG_DIR" "$HOME/Library/LaunchAgents"
chmod +x "$ROOT/service/claude-in-qq.sh"

# Deliberately absent: LimitLoadToSessionType. It belongs to the old `launchctl
# load` syntax, and under `bootstrap` it silently keeps the job from ever
# starting — state stays "not running" with no error anywhere.
cat > "$DEST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by service/install.sh. Edit that, not this. -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>

    <key>ProgramArguments</key>
    <array>
        <string>$(xml "$ROOT")/service/claude-in-qq.sh</string>
    </array>

    <key>WorkingDirectory</key>
    <string>$(xml "$ROOT")</string>

    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>$(xml "$PATH")</string>
$PROXY_ENV
        <key>LANG</key>
        <string>en_US.UTF-8</string>
    </dict>

    <key>RunAtLoad</key>
    <true/>

    <key>KeepAlive</key>
    <true/>

    <!--
      A minute-by-minute second opinion on KeepAlive, because KeepAlive can stop
      being enough: when this was written every automatic spawn on the machine
      was parked as "pended nondemand spawn", killed bridges never came back,
      and unrelated timers had silently stopped firing too — a stuck launchd
      after a failed overnight update, cleared by a reboot.

      Both mechanisms can fire at once without racing: the launch script exits
      immediately when a bridge is already alive, so the worst case of the
      redundancy is one /bin/sh per minute.
    -->
    <key>StartInterval</key>
    <integer>60</integer>

    <key>StandardOutPath</key>
    <string>$(xml "$LOG_DIR")/launchd.log</string>
    <key>StandardErrorPath</key>
    <string>$(xml "$LOG_DIR")/launchd.log</string>
</dict>
</plist>
PLIST

chmod 600 "$DEST"
plutil -lint "$DEST" >/dev/null

launchctl bootstrap "$TARGET" "$DEST"
launchctl enable "$TARGET/$LABEL"
# bootstrap from a non-Aqua context leaves RunAtLoad pending, so start it here.
launchctl kickstart -p "$TARGET/$LABEL"

sleep 3
echo "已安装 $LABEL"
launchctl print "$TARGET/$LABEL" | grep -E '^\s*(state|pid|last exit)' || true
echo
echo "日志: tail -f $LOG_DIR/bridge.log"
